# -*- coding: utf-8 -*-
"""minutes meeting generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTWa7BCwzYMi64wzJOvkTQCNrRwas-Li
"""

import pandas as pd
from datetime import datetime
print("minutes meeting generator\n")
meeting_title=input("enter meeting title: ")
date=input("enter meeting date(DD-MM-YYYY): ")
time=input("enter meeting time(HH:MM): ")
participants=input("enter participants: ")
agenda=input("enter agenda points:")
decisions=input("enter decisions: ")
action_items=input("enter action items: ")
prepared_by=input("enter prepared by: ")
participants_list=[p.strip() for p in participants.split(",") if p.strip()]
agenda_list=[a.strip() for a in agenda.split(",") if a.strip()]
decisions_list=[d.strip() for d in decisions.split(",") if d.strip()]
actions_list=[a.strip() for a in action_items.split(",") if a.strip()]
#create structured meeting
minutes={
    "Meeting_title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ",".join(participants_list),
    "Agenda": ",".join(agenda_list),
    "Decisions": ",".join(decisions_list),
    "Action_items": ",".join(actions_list),
    "Prepared_by": prepared_by,
    "Generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}
#dataframe
df=pd.DataFrame(list(minutes.items()),columns=["Field","Details"])
print("\n MINUTES MEETING GENERATOR SUCESSFULLY \n")
display(df)
#save
df.to_csv("minutes_meeting.csv", index=false)
print("\n file saved as minutes meeting.csv")