# -*- coding: utf-8 -*-
"""product review

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_KmAmuEpYX5p_S01aLHaGpW5QG49NsoP
"""

from transformers import pipeline
import pandas as pd
sentiment=pipeline("sentiment-analysis")
reviews=""" the laptop starts quickely and works smoothly for daily works. the screen quality is clear and good for watchimg videos. battery backup is average and needs charging offe."""
sentences=reviews.split(".")
pros=[]
cons=[]
for s in sentences:
    s=s.strip()
    if s==" ":
       continue
    result=sentiment(s)[0]
    if result["label"]=="POSITIVE":
      pros.append(s)
    elif result["label"]=="NEGATIVE":
       cons.append(s)
    else:
      cons.append(s)
      pros=pros[:2]
      cons=cons[:2]
      df=pd.DataFrame({"pros":pros,"cons":cons})
      df