# -*- coding: utf-8 -*-
"""sentence similarity Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mCptOvxS8ExflPjU07VfVF7azOY4O63-
"""

!pip install sentence_transformers



from sentence_transformers import SentenceTransformer,util
model=SentenceTransformer('all-MiniLM-L6-v2')
text1=input("enter text 1:")
text2=input(" enter text 2:")
embedding1=model.encode(text1)
embedding2=model.encode(text2)
similarity=util.cos_sim(embedding1,embedding2)
print("similarity score: ", round (float(similarity),2))
if similarity>0.75:
    print("similarity level: high")
elif similarity>0.4:
     print("similarity level: medium")
else:
     print("similarity level: low")