# -*- coding: utf-8 -*-
"""text generation project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O8j4ojSbNUQo1Nea7mjhdp1BDkNEv_PK
"""

!pip install transformers



from transformers import pipeline
notes_generator=pipeline(
    "text-generation",model="gpt2"
)
chapter=input("enter chapter name: ")
prompt_notes=f""" write  detalied study notes for the chapter:{chapter}
include explanation,examples, and key points."""
detailied_notes=notes_generator(
    prompt_notes,max_length=200,num_return_sequences=1
)
print("\n detailed notes:\n")
print(detailied_notes[0]['generated_text'])
prompt_summary=f"""summarize the chapter {chapter} into one page. make is simple and exam oriented."""
summary=notes_generator(
    prompt_summary,max_length=100,num_return_sequences=1
)
print("\n one_page summary:\n")
print(summary[0]['generated_text'])
prompt_definitions=f"""
list important definitions and formulas from the chapter {chapter} use bullet points
"""
definitions=notes_generator(
    prompt_definitions,max_length=200,num_return_sequences=1
)
print("\n definitions and formulas:\n")
print(definitions[0]['generated_text'])

