# -*- coding: utf-8 -*-
"""timetable  generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQhLBfBU038EencG1klTnaR42hRFBQr5
"""

import pandas as pd
import random
print("TIMETABLE GENERATOR\n")
subjects_i=input("enter subjects(comma seperated):")
days_i=input("enter days(comma seperated):")
periods=int(input("enter number of periods:")) # This input should be an integer, e.g., 6
subjects=[s.strip() for s in subjects_i.split(",")]
days=[d.strip() for d in days_i.split(",")]
if len(subjects)==0 or len(days)==0 or periods<=0:
  print("invalid input, please try again")
else:
  timetable={}
  for day in days:
    timetable[day]=random.choices(subjects,k=periods)
  df=pd.DataFrame(timetable)
  df.index=[f"period{i+1}" for i in range(periods)]
  print("\n timetable generated successfully\n")
  display(df)
  df.to_csv("timetable.csv")
  print("\n timetable saved as timetable.csv")

import pandas as pd
from datetime import datetime
print("meeting minutes generator\n")
meeting_title=input("enter meeting title:")
meeting_date=input("enter meeting date(dd/mm/yyyy):")
time=input("enter meeting time(hh:mm):")
participants=int(input("enter participants(comma separated):"))
agenda=input("enter agenda points(comma )")
decision=input("enter decision points(comma separated):")
action_items=input("enter action items(comma separated):")
prepared_by=input("enter prepared by:")
participants=[p.strip() for p in participants.split(",")]
agenda_list=[a.strip() for a in agenda.split(",")]
decision_list=[d.strip() for d in decision.split(",")]
action_list=[a.strip() for a in action_items.split(",")]
minutes={
    "meeting title":meeting_title,
    "meeting date":meeting_date,
    "meeting time":time,
    "participants":", ".join(participants_list),
    "agenda":", ".join(agenda_list),
    "decision":", ".join(decision_list),
    "action items":", ".join(action_list),
    "prepared by":prepared_by
    "generated on":datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
}
df=pd.DataFrame(list(minutes>items(),columns=["felid","detail"]))
display(df)
df.to_csv("meeting_minutes.csv",index=false)
print("\n file saved as meeting_minutes.csv")



import pandas as pd
from datetime import datetime
print("meeting minutes generator\n")
meeting_title=input("enter meeting title:")
meeting_date=input("enter meeting date(dd/mm/yyyy):")
time=input("enter meeting time(hh:mm):")
participants=(input("enter participants(comma separated):"))
agenda=input("enter agenda points(comma )")
decision=input("enter decision points(comma separated):")
action_items=input("enter action items(comma separated):")
prepared_by=input("enter prepared by:")
participants=[p.strip() for p in participants.split(",")]
agenda_list=[a.strip() for a in agenda.split(",")]
decision_list=[d.strip() for d in decision.split(",")]
action_list=[a.strip() for a in action_items.split(",")]
minutes={
    "meeting title":meeting_title,
    "meeting date":meeting_date,
    "meeting time":time,
    "participants":", ".join(participants_list),
    "agenda":", ".join(agenda_list),
    "decision":", ".join(decision_list),
    "action items":", ".join(action_list),
    "prepared by":prepared_by
    "generated on":datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
}
df=pd.DataFrame(list(minutes.items(),columns=["field","detail"]))
display(df)
df.to_csv("meeting_minutes.csv",index=false)
print("\n file saved as meeting_minutes.csv")